#+title: Pixa Emacs
#+DATE: 2023-06-18
#+DESCRIPTION: Personal Emacs configuration of Pixalesce
#+AUTHOR: Pixalesce
#+EMAIL: pixalesce@gmail.com
Welcome to my personal Emacs configuration. Feel free to make a copy of my files to configure your own experience of emacs :)

** Notes
As =user-emacs-directory= differs by computer and operating system, do note that the location of your =init.el= might be placed in a different location. For me, =user-emacs-directory= is defaulted to =.emacs.d=, so that's where my init file goes.

Setup of *LSP* is based on the languages that I most commonly use at the moment. Should I learn other languages, the necessary language servers will be set up as well.

*Org Mode setup*, including but not limited to org agenda and org capture template configurations, will be completed at a later date as it is not my current priority. I will probably look into more given time and greater familiarisation with Emacs.

The configuration will load up automatically on the initial load of Emacs, and the configuration can be further personalised thereafter.

*** Visualisation of My Directory Tree
#+begin_src bash
.emacs.d
├── config
│   └── config.org
└── init.el
#+end_src
** Completed Features
- Package Manager
- Completion Support
- Evil Mode
- Fonts
- Project Management
- File Management
- Github Integration
- LSP
  + Python
  + Rust, TOML
  + Java
  + C, C++
  + JavaScript, TypeScript
  + HTML, CSS
** Ongoing Additions
- LSP
- Dashboard
- Notion Integration
- Email Integration
- Org Mode Setup
- Quality of Life
